import { FlatConfig, includeIgnoreFile } from '@eslint/compat';
import format from 'eslint-plugin-format';
import { defineConfig } from 'eslint/config';
import { fileURLToPath } from 'node:url';

const gitignorePath = fileURLToPath(new URL('.gitignore', import.meta.url));

const dprint = {
  typescript: {
    plugin: 'node_modules/@dprint/typescript/plugin.wasm',
    options: {
      'lineWidth': 80,
      'indentWidth': 2,
      'useTabs': false,
      'semiColons': 'always',
      'quoteStyle': 'preferSingle',
      'jsx.quoteStyle': 'preferDouble',
      'quoteProps': 'consistent',
      'newLineKind': 'lf',
      'useBraces': 'whenNotSingleLine',
      'forInStatement.useBraces': 'whenNotSingleLine',
      'forOfStatement.useBraces': 'whenNotSingleLine',
      'forStatement.useBraces': 'whenNotSingleLine',
      'ifStatement.useBraces': 'whenNotSingleLine',
      'whileStatement.useBraces': 'whenNotSingleLine',
      'bracePosition': 'sameLine',
      'arrowFunction.bracePosition': 'sameLine',
      'classDeclaration.bracePosition': 'sameLine',
      'classExpression.bracePosition': 'sameLine',
      'constructor.bracePosition': 'sameLine',
      'doWhileStatement.bracePosition': 'sameLine',
      'enumDeclaration.bracePosition': 'sameLine',
      'forInStatement.bracePosition': 'sameLine',
      'forOfStatement.bracePosition': 'sameLine',
      'forStatement.bracePosition': 'sameLine',
      'functionDeclaration.bracePosition': 'sameLine',
      'functionExpression.bracePosition': 'sameLine',
      'getAccessor.bracePosition': 'sameLine',
      'ifStatement.bracePosition': 'sameLine',
      'interfaceDeclaration.bracePosition': 'sameLine',
      'moduleDeclaration.bracePosition': 'sameLine',
      'method.bracePosition': 'sameLine',
      'setAccessor.bracePosition': 'sameLine',
      'staticBlock.bracePosition': 'sameLine',
      'switchStatement.bracePosition': 'sameLine',
      'switchCase.bracePosition': 'sameLine',
      'tryStatement.bracePosition': 'sameLine',
      'whileStatement.bracePosition': 'sameLine',
      'singleBodyPosition': 'sameLine',
      'forInStatement.singleBodyPosition': 'sameLine',
      'forOfStatement.singleBodyPosition': 'sameLine',
      'forStatement.singleBodyPosition': 'sameLine',
      'ifStatement.singleBodyPosition': 'sameLine',
      'whileStatement.singleBodyPosition': 'sameLine',
      'nextControlFlowPosition': 'sameLine',
      'ifStatement.nextControlFlowPosition': 'sameLine',
      'tryStatement.nextControlFlowPosition': 'sameLine',
      'doWhileStatement.nextControlFlowPosition': 'sameLine',
      'trailingCommas': 'onlyMultiLine',
      'arguments.trailingCommas': 'onlyMultiLine',
      'parameters.trailingCommas': 'onlyMultiLine',
      'arrayExpression.trailingCommas': 'onlyMultiLine',
      'arrayPattern.trailingCommas': 'onlyMultiLine',
      'enumDeclaration.trailingCommas': 'onlyMultiLine',
      'exportDeclaration.trailingCommas': 'onlyMultiLine',
      'importDeclaration.trailingCommas': 'onlyMultiLine',
      'objectExpression.trailingCommas': 'onlyMultiLine',
      'objectPattern.trailingCommas': 'onlyMultiLine',
      'tupleType.trailingCommas': 'onlyMultiLine',
      'typeLiteral.trailingCommas': 'onlyMultiLine',
      'typeParameters.trailingCommas': 'onlyMultiLine',
      'operatorPosition': 'nextLine',
      'binaryExpression.operatorPosition': 'nextLine',
      'conditionalExpression.operatorPosition': 'nextLine',
      'conditionalType.operatorPosition': 'nextLine',
      'preferHanging': false,
      'arguments.preferHanging': 'onlySingleItem',
      'arrayExpression.preferHanging': 'onlySingleItem',
      'arrayPattern.preferHanging': false,
      'doWhileStatement.preferHanging': false,
      'exportDeclaration.preferHanging': false,
      'extendsClause.preferHanging': false,
      'forInStatement.preferHanging': false,
      'forOfStatement.preferHanging': false,
      'forStatement.preferHanging': false,
      'ifStatement.preferHanging': false,
      'implementsClause.preferHanging': false,
      'importDeclaration.preferHanging': false,
      'jsxAttributes.preferHanging': false,
      'objectExpression.preferHanging': false,
      'objectPattern.preferHanging': false,
      'parameters.preferHanging': 'onlySingleItem',
      'sequenceExpression.preferHanging': false,
      'switchStatement.preferHanging': false,
      'tupleType.preferHanging': 'onlySingleItem',
      'typeLiteral.preferHanging': false,
      'typeParameters.preferHanging': 'onlySingleItem',
      'unionAndIntersectionType.preferHanging': false,
      'variableStatement.preferHanging': false,
      'whileStatement.preferHanging': false,
      'preferSingleLine': true,
      'arrayExpression.preferSingleLine': true,
      'arrayPattern.preferSingleLine': true,
      'arguments.preferSingleLine': true,
      'binaryExpression.preferSingleLine': true,
      'computed.preferSingleLine': true,
      'conditionalExpression.preferSingleLine': true,
      'conditionalType.preferSingleLine': true,
      'decorators.preferSingleLine': true,
      'exportDeclaration.preferSingleLine': true,
      'forStatement.preferSingleLine': true,
      'importDeclaration.preferSingleLine': true,
      'jsxAttributes.preferSingleLine': true,
      'jsxElement.preferSingleLine': true,
      'mappedType.preferSingleLine': true,
      'memberExpression.preferSingleLine': true,
      'objectExpression.preferSingleLine': false,
      'objectPattern.preferSingleLine': true,
      'parameters.preferSingleLine': true,
      'parentheses.preferSingleLine': true,
      'tupleType.preferSingleLine': true,
      'typeLiteral.preferSingleLine': true,
      'typeParameters.preferSingleLine': true,
      'unionAndIntersectionType.preferSingleLine': true,
      'variableStatement.preferSingleLine': true,
      'arrowFunction.useParentheses': 'force',
      'binaryExpression.linePerExpression': false,
      'jsx.bracketPosition': 'nextLine',
      'jsxOpeningElement.bracketPosition': 'nextLine',
      'jsxSelfClosingElement.bracketPosition': 'nextLine',
      'jsx.forceNewLinesSurroundingContent': false,
      'jsx.multiLineParens': 'prefer',
      'memberExpression.linePerExpression': true,
      'typeLiteral.separatorKind': 'semiColon',
      'typeLiteral.separatorKind.singleLine': 'semiColon',
      'typeLiteral.separatorKind.multiLine': 'semiColon',
      'enumDeclaration.memberSpacing': 'newLine',
      'spaceAround': false,
      'arguments.spaceAround': false,
      'arrayExpression.spaceAround': false,
      'arrayPattern.spaceAround': false,
      'catchClause.spaceAround': false,
      'doWhileStatement.spaceAround': false,
      'forInStatement.spaceAround': false,
      'forOfStatement.spaceAround': false,
      'forStatement.spaceAround': false,
      'ifStatement.spaceAround': false,
      'parameters.spaceAround': false,
      'parenExpression.spaceAround': false,
      'switchStatement.spaceAround': false,
      'tupleType.spaceAround': false,
      'whileStatement.spaceAround': false,
      'spaceSurroundingProperties': true,
      'objectExpression.spaceSurroundingProperties': true,
      'objectPattern.spaceSurroundingProperties': true,
      'typeLiteral.spaceSurroundingProperties': true,
      'binaryExpression.spaceSurroundingBitwiseAndArithmeticOperator': true,
      'commentLine.forceSpaceAfterSlashes': true,
      'constructor.spaceBeforeParentheses': false,
      'constructorType.spaceAfterNewKeyword': false,
      'constructSignature.spaceAfterNewKeyword': false,
      'doWhileStatement.spaceAfterWhileKeyword': true,
      'exportDeclaration.spaceSurroundingNamedExports': true,
      'forInStatement.spaceAfterForKeyword': true,
      'forOfStatement.spaceAfterForKeyword': true,
      'forStatement.spaceAfterForKeyword': true,
      'forStatement.spaceAfterSemiColons': true,
      'functionDeclaration.spaceBeforeParentheses': false,
      'functionExpression.spaceBeforeParentheses': false,
      'functionExpression.spaceAfterFunctionKeyword': false,
      'functionExpression.flatIife': false,
      'getAccessor.spaceBeforeParentheses': false,
      'ifStatement.spaceAfterIfKeyword': true,
      'importDeclaration.spaceSurroundingNamedImports': true,
      'jsxSelfClosingElement.spaceBeforeSlash': true,
      'jsxExpressionContainer.spaceSurroundingExpression': false,
      'method.spaceBeforeParentheses': false,
      'setAccessor.spaceBeforeParentheses': false,
      'taggedTemplate.spaceBeforeLiteral': false,
      'typeAnnotation.spaceBeforeColon': false,
      'typeAssertion.spaceBeforeExpression': true,
      'whileStatement.spaceAfterWhileKeyword': true,
      'module.sortImportDeclarations': 'caseInsensitive',
      'module.sortExportDeclarations': 'caseInsensitive',
      'exportDeclaration.sortNamedExports': 'caseInsensitive',
      'exportDeclaration.sortTypeOnlyExports': 'last',
      'importDeclaration.sortNamedImports': 'caseInsensitive',
      'importDeclaration.sortTypeOnlyImports': 'last',
      'ignoreNodeCommentText': 'dprint-ignore',
      'ignoreFileCommentText': 'dprint-ignore-file',
      'exportDeclaration.forceSingleLine': true,
      'importDeclaration.forceSingleLine': true,
      'exportDeclaration.forceMultiLine': 'never',
      'importDeclaration.forceMultiLine': 'never',
    },
  },
  json: {
    plugin: 'node_modules/@dprint/json/plugin.wasm',
    options: {
      'lineWidth': 80,
      'indentWidth': 2,
      'useTabs': false,
      'newLineKind': 'lf',
      'commentLine.forceSpaceAfterSlashes': true,
      'preferSingleLine': false,
      'array.preferSingleLine': false,
      'object.preferSingleLine': false,
      'trailingCommas': 'jsonc',
      'jsonTrailingCommaFiles': [
        '.vscode/extensions.json',
        '.vscode/launch.json',
        '.vscode/settings.json',
        '.vscode/tasks.json',
        'docs/tsconfig.json',
        'playground/server/tsconfig.json',
        'playground/tsconfig.json',
        'src/runtime/server/tsconfig.json',
        'tsconfig.json',
      ],
      'ignoreNodeCommentText': 'dprint-ignore',
    },
  },
  markdown: {
    plugin: 'node_modules/@dprint/markdown/plugin.wasm',
    options: {
      'lineWidth': 80,
      'newLineKind': 'lf',
      'textWrap': 'always',
      'wrapUnspacedScripts': false,
      'emphasisKind': 'underscores',
      'strongKind': 'asterisks',
      'hardBreakKind': 'backslash',
      'maxBlankLines': 1,
      'heading.kind': 'atx',
      'heading.blankLinesAbove': 1,
      'list.unorderedMarker': 'dashes',
      'list.indentKind': 'commonMark',
      'codeBlock.skipFormat': false,
      'codeBlock.raiseSyntaxErrors': false,
      'codeBlock.preserveIndentation': false,
      'codeBlock.preserveBlankLines': false,
      'codeBlock.useTabs': false,
      'codeBlock.indentWidth': 2,
      'html.skipFormat': false,
      'html.useTabs': false,
      'html.indentWidth': 2,
      'html.selfClosingSpace': true,
      'html.preferSingleLine': false,
      'table.skipFormat': false,
      'table.cellPadding': 'align',
      'ignoreDirective': 'dprint-ignore',
      'ignoreFileDirective': 'dprint-ignore-file',
      'ignoreStartDirective': 'dprint-ignore-start',
      'ignoreEndDirective': 'dprint-ignore-end',
      'tags': undefined,
    },
  },
  dockerfile: {
    plugin: 'node_modules/@dprint/dockerfile/plugin.wasm',
    options: {
      lineWidth: 80,
      newLineKind: 'lf',
      healthcheckCmdNewLine: false,
      indentStages: false,
      indentWidth: 2,
    },
  },
  malva: {
    plugin: 'node_modules/dprint-plugin-malva/plugin.wasm',
    options: {
      'printWidth': 80,
      'useTabs': false,
      'indentWidth': 2,
      'lineBreak': 'lf',
      'hexCase': 'lower',
      'hexColorLength': 'short',
      'quotes': 'preferSingle',
      'attrSelector.quotes': 'alwaysDouble',
      'operatorLinebreak': 'before',
      'blockSelectorLinebreak': 'consistent',
      'omitNumberLeadingZero': false,
      'trailingComma': true,
      'formatComments': true,
      'alignComments': true,
      'linebreakInPseudoParens': true,
      'declarationOrder': 'alphabetical',
      'declarationOrderGroupBy': 'nonDeclaration',
      'singleLineBlockThreshold': null,
      'keyframeSelectorNotation': 'keyword',
      'attrValueQuotes': 'always',
      'preferSingleLine': true,
      'selectors.preferSingleLine': true,
      'functionArgs.preferSingleLine': true,
      'sassContentAtRule.preferSingleLine': false,
      'sassIncludeAtRule.preferSingleLine': false,
      'sassMap.preferSingleLine': false,
      'sassModuleConfig.preferSingleLine': false,
      'sassParams.preferSingleLine': false,
      'lessImportOptions': true,
      'lessMixinArgs.preferSingleLine': false,
      'lessMixinParams.preferSingleLine': false,
      'singleLineTopLevelDeclarations': false,
      'fontFamilyNames': 'consistent',
      'nthPlusSpacing': true,
      'selectorOverrideCommentDirective': 'malva-selector-override',
      'ignoreCommentDirective': 'malva-ignore',
      'ignoreFileCommentDirective': 'malva-ignore-file',
    },
  },
  markup: {
    plugin: 'node_modules/dprint-plugin-markup/plugin.wasm',
    options: {
      'printWidth': 80,
      'useTabs': false,
      'indentWidth': 2,
      'lineBreak': 'lf',
      'quotes': 'double',
      'formatComments': true,
      'scriptIndent': false,
      'html.scriptIndent': true,
      'vue.scriptIndent': false,
      'svelte.scriptIndent': true,
      'astro.scriptIndent': true,
      'styleIndent': false,
      'html.styleIndent': true,
      'vue.styleIndent': false,
      'svelte.styleIndent': true,
      'astro.styleIndent': true,
      'closingBracketSameLine': false,
      'closingTagLineBreakForEmpty': 'fit',
      'maxAttrsPerLine': 1,
      'preferAttrsSingleLine': false,
      'singleAttrSameLine': true,
      'html.normal.selfClosing': false,
      'html.void.selfClosing': false,
      'component.selfClosing': true,
      'svg.selfClosing': true,
      'mathml.selfClosing': true,
      'whitespaceSensitivity': 'ignore',
      'component.whitespaceSensitivity': 'ignore',
      'doctypeKeywordCase': 'lower',
      'vBindStyle': 'short',
      'vOnStyle': 'short',
      'vForDelimiterStyle': 'in',
      'vSlotStyle': 'short',
      'component.vSlotStyle': 'short',
      'default.vSlotStyle': 'short',
      'named.vSlotStyle': 'short',
      'vBindSameNameShortHand': true,
      'vueComponentCase': 'pascalCase',
      'strictSvelteAttr': false,
      'svelteAttrShorthand': true,
      'svelteDirectiveShorthand': true,
      'astroAttrShorthand': true,
      'angularNextControlFlowSameLine': true,
      'scriptFormatter': 'dprint',
      'ignoreCommentDirective': 'markup-fmt-ignore',
      'ignoreFileCommentDirective': 'markup-fmt-ignore-file',
    },
  },
  yaml: {
    plugin: 'node_modules/dprint-plugin-yaml/plugin.wasm',
    options: {
      'printWidth': 80,
      'indentWidth': 2,
      'lineBreak': 'lf',
      'quotes': 'preferSingle',
      'trailingComma': true,
      'formatComments': true,
      'indentBlockSequenceInMap': true,
      'braceSpacing': true,
      'bracketSpacing': false,
      'dashSpacing': 'oneSpace',
      'preferSingleLine': false,
      'flowSequence.preferSingleLine': false,
      'flowMap.preferSingleLine': false,
      'trimTrailingWhitespaces': true,
      'trimTrailingZero': false,
      'proseWrap': 'always',
      'ignoreCommentDirective': 'pretty-yaml-ignore',
    },
  },
} as const;

const useDprint = (
  files: string[],
  plugins: { plugin: string; options: Record<string, unknown>; }[],
): FlatConfig => ({
  files,
  plugins: { format },
  languageOptions: { parser: format.parserPlain },
  rules: { 'format/dprint': ['error', { plugins }] },
});

export default defineConfig([
  includeIgnoreFile(gitignorePath, 'Imported `.gitignore` patterns'),
  useDprint(['**/*.{ts,js,tsx,jsx}'], [dprint.typescript]),
  useDprint(['**/*.json'], [dprint.json]),
  useDprint(['**/*.md'], [dprint.markdown]),
  useDprint(['**/Dockerfile*'], [dprint.dockerfile]),
  useDprint(['**/*.{css,scss,sass,less}'], [dprint.malva]),
  useDprint([
    '**/*.{html,htm,vue,svelte,astro,jinja,j2,jinja2,twig,njk,nunjucks,vto,mustache,mst,xml,svg}',
  ], [dprint.markup, dprint.typescript, dprint.malva]),
  useDprint(['**/*.{yaml,yml}'], [dprint.yaml]),
]);
