import { FlatConfig, includeIgnoreFile } from '@eslint/compat';
import format from 'eslint-plugin-format';
import { defineConfig } from 'eslint/config';
import { fileURLToPath } from 'node:url';

const gitignorePath = fileURLToPath(new URL('.gitignore', import.meta.url));

const dprint = {
  typescript: {
    plugin: 'node_modules/@dprint/typescript/plugin.wasm',
    options: {
      'lineWidth': 80,
      'indentWidth': 2,
      'useTabs': false,
      'semiColons': 'always',
      'quoteStyle': 'preferSingle',
      'jsx.quoteStyle': 'preferDouble',
      'quoteProps': 'consistent',
      'newLineKind': 'lf',
      'useBraces': 'whenNotSingleLine',
      'bracePosition': 'sameLine',
      'singleBodyPosition': 'sameLine',
      'nextControlFlowPosition': 'sameLine',
      'trailingCommas': 'onlyMultiLine',
      'operatorPosition': 'nextLine',
      'preferHanging': false,
      'arguments.preferHanging': 'onlySingleItem',
      'arrayExpression.preferHanging': 'onlySingleItem',
      'parameters.preferHanging': 'onlySingleItem',
      'tupleType.preferHanging': 'onlySingleItem',
      'typeParameters.preferHanging': 'onlySingleItem',
      'preferSingleLine': true,
      'arrowFunction.useParentheses': 'force',
      'binaryExpression.linePerExpression': false,
      'jsx.bracketPosition': 'nextLine',
      'jsx.forceNewLinesSurroundingContent': false,
      'jsx.multiLineParens': 'prefer',
      'memberExpression.linePerExpression': true,
      'typeLiteral.separatorKind': 'semiColon',
      'enumDeclaration.memberSpacing': 'newLine',
      'spaceAround': false,
      'spaceSurroundingProperties': true,
      'binaryExpression.spaceSurroundingBitwiseAndArithmeticOperator': true,
      'commentLine.forceSpaceAfterSlashes': true,
      'constructor.spaceBeforeParentheses': false,
      'constructorType.spaceAfterNewKeyword': false,
      'constructSignature.spaceAfterNewKeyword': false,
      'doWhileStatement.spaceAfterWhileKeyword': true,
      'exportDeclaration.spaceSurroundingNamedExports': true,
      'forInStatement.spaceAfterForKeyword': true,
      'forOfStatement.spaceAfterForKeyword': true,
      'forStatement.spaceAfterForKeyword': true,
      'forStatement.spaceAfterSemiColons': true,
      'functionDeclaration.spaceBeforeParentheses': false,
      'functionExpression.spaceBeforeParentheses': false,
      'functionExpression.spaceAfterFunctionKeyword': false,
      'getAccessor.spaceBeforeParentheses': false,
      'ifStatement.spaceAfterIfKeyword': true,
      'importDeclaration.spaceSurroundingNamedImports': true,
      'jsxSelfClosingElement.spaceBeforeSlash': true,
      'jsxExpressionContainer.spaceSurroundingExpression': false,
      'method.spaceBeforeParentheses': false,
      'setAccessor.spaceBeforeParentheses': false,
      'taggedTemplate.spaceBeforeLiteral': false,
      'typeAnnotation.spaceBeforeColon': false,
      'typeAssertion.spaceBeforeExpression': true,
      'whileStatement.spaceAfterWhileKeyword': true,
      'module.sortImportDeclarations': 'caseInsensitive',
      'module.sortExportDeclarations': 'caseInsensitive',
      'exportDeclaration.sortNamedExports': 'caseInsensitive',
      'exportDeclaration.sortTypeOnlyExports': 'last',
      'importDeclaration.sortNamedImports': 'caseInsensitive',
      'importDeclaration.sortTypeOnlyImports': 'last',
      'ignoreNodeCommentText': 'dprint-ignore',
      'ignoreFileCommentText': 'dprint-ignore-file',
      'exportDeclaration.forceSingleLine': true,
      'importDeclaration.forceSingleLine': true,
      'exportDeclaration.forceMultiLine': 'never',
      'importDeclaration.forceMultiLine': 'never',
    },
  },
  json: {
    plugin: 'node_modules/@dprint/json/plugin.wasm',
    options: {
      'lineWidth': 80,
      'indentWidth': 2,
      'useTabs': false,
      'newLineKind': 'lf',
      'commentLine.forceSpaceAfterSlashes': true,
      'preferSingleLine': false,
      'trailingCommas': 'jsonc',
      'jsonTrailingCommaFiles': [
        '.vscode/extensions.json',
        '.vscode/launch.json',
        '.vscode/settings.json',
        '.vscode/tasks.json',
        'docs/tsconfig.json',
        'playground/server/tsconfig.json',
        'playground/tsconfig.json',
        'src/runtime/server/tsconfig.json',
        'tsconfig.json',
      ],
      'ignoreNodeCommentText': 'dprint-ignore',
    },
  },
  markdown: {
    plugin: 'node_modules/@dprint/markdown/plugin.wasm',
    options: {
      lineWidth: 80,
      newLineKind: 'lf',
      textWrap: 'always',
      emphasisKind: 'underscores',
      strongKind: 'asterisks',
      unorderedListKind: 'dashes',
      headingKind: 'atx',
      ignoreDirective: 'dprint-ignore',
      ignoreFileDirective: 'dprint-ignore-file',
      ignoreStartDirective: 'dprint-ignore-start',
      ignoreEndDirective: 'dprint-ignore-end',
    },
  },
  dockerfile: {
    plugin: 'node_modules/@dprint/dockerfile/plugin.wasm',
    options: { lineWidth: 80, newLineKind: 'lf' },
  },
  malva: {
    plugin: 'node_modules/dprint-plugin-malva/plugin.wasm',
    options: {
      'printWidth': 80,
      'useTabs': false,
      'indentWidth': 2,
      'lineBreak': 'lf',
      'hexCase': 'lower',
      'hexColorLength': 'short',
      'quotes': 'preferSingle',
      'attrSelector.quotes': 'alwaysDouble',
      'operatorLinebreak': 'before',
      'blockSelectorLinebreak': 'consistent',
      'omitNumberLeadingZero': false,
      'trailingComma': true,
      'formatComments': true,
      'alignComments': true,
      'linebreakInPseudoParens': true,
      'declarationOrder': 'alphabetical',
      'declarationOrderGroupBy': 'nonDeclaration',
      'singleLineBlockThreshold': null,
      'keyframeSelectorNotation': 'keyword',
      'attrValueQuotes': 'always',
      'preferSingleLine': true,
      'sassContentAtRule.preferSingleLine': false,
      'sassIncludeAtRule.preferSingleLine': false,
      'sassMap.preferSingleLine': false,
      'sassModuleConfig.preferSingleLine': false,
      'sassParams.preferSingleLine': false,
      'lessMixinArgs.preferSingleLine': false,
      'lessMixinParams.preferSingleLine': false,
      'singleLineTopLevelDeclarations': false,
      'selectorOverrideCommentDirective': 'malva-selector-override',
      'ignoreCommentDirective': 'malva-ignore',
      'ignoreFileCommentDirective': 'malva-ignore-file',
    },
  },
  markup: {
    plugin: 'node_modules/dprint-plugin-markup/plugin.wasm',
    options: {
      'printWidth': 80,
      'useTabs': false,
      'indentWidth': 2,
      'lineBreak': 'lf',
      'quotes': 'double',
      'formatComments': true,
      'scriptIndent': false,
      'html.scriptIndent': true,
      'styleIndent': false,
      'html.styleIndent': true,
      'closingBracketSameLine': false,
      'closingTagLineBreakForEmpty': 'fit',
      'maxAttrsPerLine': 1,
      'preferAttrsSingleLine': false,
      'singleAttrSameLine': true,
      'html.normal.selfClosing': false,
      'html.void.selfClosing': false,
      'component.selfClosing': true,
      'svg.selfClosing': true,
      'mathml.selfClosing': true,
      'whitespaceSensitivity': 'ignore',
      'doctypeKeywordCase': 'lower',
      'vBindStyle': 'short',
      'vOnStyle': 'short',
      'vForDelimiterStyle': 'in',
      'vSlotStyle': 'short',
      'vBindSameNameShortHand': true,
      'vueComponentCase': 'pascalCase',
      'strictSvelteAttr': false,
      'svelteAttrShorthand': true,
      'svelteDirectiveShorthand': true,
      'astroAttrShorthand': true,
      'angularNextControlFlowSameLine': true,
      'scriptFormatter': 'dprint',
      'ignoreCommentDirective': 'markup-fmt-ignore',
      'ignoreFileCommentDirective': 'markup-fmt-ignore-file',
    },
  },
  yaml: {
    plugin: 'node_modules/dprint-plugin-yaml/plugin.wasm',
    options: {
      printWidth: 80,
      indentWidth: 2,
      lineBreak: 'lf',
      quotes: 'preferSingle',
      trailingComma: true,
      formatComments: true,
      indentBlockSequenceInMap: true,
      braceSpacing: true,
      bracketSpacing: false,
      dashSpacing: 'oneSpace',
      preferSingleLine: false,
      trimTrailingWhitespaces: true,
      trimTrailingZero: false,
      proseWrap: 'always',
      ignoreCommentDirective: 'pretty-yaml-ignore',
    },
  },
} as const;

const useDprint = (
  files: string[],
  plugins: { plugin: string; options: Record<string, unknown>; }[],
): FlatConfig => ({
  files,
  plugins: { format },
  languageOptions: { parser: format.parserPlain },
  rules: { 'format/dprint': ['error', { plugins }] },
});

export default defineConfig([
  includeIgnoreFile(gitignorePath, 'Imported `.gitignore` patterns'),
  useDprint(['**/*.{ts,js,tsx,jsx}'], [dprint.typescript]),
  useDprint(['**/*.json'], [dprint.json]),
  useDprint(['**/*.md'], [dprint.markdown]),
  useDprint(['**/Dockerfile*'], [dprint.dockerfile]),
  useDprint(['**/*.{css,scss,sass,less}'], [dprint.malva]),
  useDprint([
    '**/*.{html,htm,vue,svelte,astro,jinja,j2,jinja2,twig,njk,nunjucks,vto,mustache,mst,xml,svg}',
  ], [dprint.markup, dprint.typescript, dprint.malva]),
  useDprint(['**/*.{yaml,yml}'], [dprint.yaml]),
]);
